stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "18"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn-cache/

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - yarn install --frozen-lockfile
    - yarn run lint:check
    - yarn run typecheck
    - yarn run test:ci
  artifacts:
    reports:
      junit: junit.xml

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - yarn install --frozen-lockfile
    - yarn run build:native
    - yarn run build
  artifacts:
    paths:
      - .next/
      - out/
  only:
    - main
    - master
    - develop

deploy_production:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - yarn install --frozen-lockfile --production
    - yarn run deploy:prod
  environment:
    name: production
    url: ${PRODUCTION_URL}
  dependencies:
    - build
  only:
    - main
    - master
  variables:
    DEPLOY_TOKEN: ${DEPLOY_TOKEN}
    PRODUCTION_URL: ${PRODUCTION_URL}

deploy_staging:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - yarn install --frozen-lockfile --production
    - yarn run deploy:staging
  environment:
    name: staging
    url: ${STAGING_URL}
  dependencies:
    - build
  only:
    - develop
  variables:
    DEPLOY_TOKEN: ${DEPLOY_TOKEN}
    STAGING_URL: ${STAGING_URL}
